//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLTourDucLich.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourView
    {
        public string MaTour { get; set; }
        public string TenTour { get; set; }
        public Nullable<decimal> GiaNguoiLon { get; set; }
        public Nullable<decimal> GiaTreEm { get; set; }
        public Nullable<int> NoiDi { get; set; }
        public Nullable<int> NoiDen { get; set; }
        public string MoTa { get; set; }
    }
}
